language: java
#- 3.3
notifications:
email: false
# Setup anaconda
before_install:

install:
 - sudo apt-get install unzip
 - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
 - echo "deb http://download.virtualbox.org/virtualbox/debian trusty contrib"| sudo tee --append /etc/apt/sources.list
 - sudo apt-get update
 - sudo apt-get install virtualbox-4.3
 - sudo apt-get remove virtualbox-dkms
 - sudo apt-get install virtualbox-dkms
 - cd showyourworking/deployment/packer/
 - wget https://releases.hashicorp.com/packer/0.10.0/packer_0.10.0_linux_amd64.zip
 - unzip packer_0.10.0_linux_amd64.zip
 - ./packer build -only=virtualbox-iso base_box.json 
