language: java
#- 3.3
notifications:
email: false
# Setup anaconda
before_install:

install:
 - sudo apt-get install unzip
 - wget http://download.virtualbox.org/virtualbox/5.0.18/virtualbox-5.0_5.0.18-106667~Ubuntu~trusty_amd64.deb
 - sudo dpkg -i virtualbox-5.0_5.0.18-106667~Ubuntu~trusty_amd64.deb
 - cd showyourworking/deployment/packer/
 - wget https://releases.hashicorp.com/packer/0.10.0/packer_0.10.0_linux_amd64.zip
 - unzip packer_0.10.0_linux_amd64.zip
 - ./packer build -only=virtualbox-iso base_box.json 
