language: java
#- 3.3
notifications:
email: false
# Setup anaconda
before_install:

install:
 - sudo apt-get install unzip
 - sudo apt-add-repository "deb http://download.virtualbox.org/virtualbox/debian trusty contrib"
 - sudo apt-get update
 - sudo apt-get install virtualbox
 - cd showyourworking/deployment/packer/
 - wget https://releases.hashicorp.com/packer/0.10.0/packer_0.10.0_linux_amd64.zip
 - unzip packer_0.10.0_linux_amd64.zip
 - ./packer build -only=virtualbox-iso base_box.json 
